In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
scores=pd.read_csv("data_safe_copy.csv")

In [4]:
len(scores)#number of rows

300

In [5]:
scores.head(5)

  student_id cohort   module assignment  score
0       S001  alpha  Module1         A1     78
1       S001  alpha  Module1         A2     84
2       S001  alpha  Module2         A1     79
3       S001  alpha  Module2         A2     86
4       S001  alpha  Module3         A1     81

In [6]:
scores.info()

<class 'pandas.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   student_id  300 non-null    str
 1   cohort      300 non-null    str
 2   module      300 non-null    str
 3   assignment  300 non-null    str
 4   score       300 non-null    int64
dtypes: int64(1), str(4)
memory usage: 11.8 KB

In [7]:
scores["score"].dtype

dtype('int64')

TASK2

In [8]:
scores["student_id"].unique()

<StringArray>
['S001', 'S002', 'S003', 'S004', 'S005', 'S006', 'S007', 'S008', 'S009',
 'S010', 'S011', 'S012', 'S013', 'S014', 'S015', 'S016', 'S017', 'S018',
 'S019', 'S020', 'S021', 'S022', 'S023', 'S024', 'S025', 'S026', 'S027',
 'S028', 'S029', 'S030', 'S031', 'S032', 'S033', 'S034', 'S035', 'S036',
 'S037', 'S038', 'S039', 'S040', 'S041', 'S042', 'S043', 'S044', 'S045',
 'S046', 'S047', 'S048', 'S049', 'S050']
Length: 50, dtype: str

In [9]:
np.random.seed(40)
roster=pd.DataFrame({
  "student_id": ['S011', 'S002', 'S013','S020','S061', 'S062', 'S063', 'S064', 'S065', 'S066',
 'S067', 'S068', 'S069', 'S070', ],
  "status": np.random.choice(["active","inactive"],size=14)
})

In [10]:
roster

   student_id    status
0        S011    active
1        S002  inactive
2        S013  inactive
3        S020  inactive
4        S061    active
5        S062    active
6        S063    active
7        S064  inactive
8        S065    active
9        S066  inactive
10       S067    active
11       S068  inactive
12       S069  inactive
13       S070    active

In [11]:
merged=pd.merge(scores,roster,on="student_id",how="left")
merged

    student_id cohort   module assignment  score status
0         S001  alpha  Module1         A1     78    NaN
1         S001  alpha  Module1         A2     84    NaN
2         S001  alpha  Module2         A1     79    NaN
3         S001  alpha  Module2         A2     86    NaN
4         S001  alpha  Module3         A1     81    NaN
..         ...    ...      ...        ...    ...    ...
295       S050   beta  Module1         A2     77    NaN
296       S050   beta  Module2         A1     73    NaN
297       S050   beta  Module2         A2     76    NaN
298       S050   beta  Module3         A1     75    NaN
299       S050   beta  Module3         A2     78    NaN

[300 rows x 6 columns]

In [12]:
merged.isna().any()#to check any missing value

student_id    False
cohort        False
module        False
assignment    False
score         False
status         True
dtype: bool

In [13]:
merged["status"].isna().sum()#show number of missing values

np.int64(276)

TASK3

In [14]:
import pandas as pd
avg_by_module = scores.groupby(['cohort', 'module'], as_index=False)['score'].mean()

avg_by_module.rename(columns={'score': 'avg_score'}, inplace=True)
avg_by_module

  cohort   module  avg_score
0  alpha  Module1  77.970588
1  alpha  Module2  78.382353
2  alpha  Module3  79.794118
3   beta  Module1  78.647059
4   beta  Module2  78.411765
5   beta  Module3  80.029412
6  gamma  Module1  76.218750
7  gamma  Module2  76.468750
8  gamma  Module3  77.843750

In [15]:
avg_by_coh=scores.groupby("cohort")["score"].mean()
avg_by_coh

cohort
alpha    78.715686
beta     79.029412
gamma    76.843750
Name: score, dtype: float64

In [16]:
alpha_avg = avg_by_module[avg_by_module['cohort'] == 'alpha']['avg_score'].mean()
beta_avg = avg_by_module[avg_by_module['cohort'] == 'beta']['avg_score'].mean()
gamma_avg = avg_by_module[avg_by_module['cohort'] == 'gamma']['avg_score'].mean()
print(alpha_avg, beta_avg, gamma_avg)#to compare averages

78.71568627450979 79.02941176470588 76.84375

TASK4

In [26]:
import pandas as pd
student_module_report = scores.pivot_table(
    index='student_id',
    columns='module',
    values='score',
    aggfunc='mean'
)
print(student_module_report)

module      Module1  Module2  Module3
student_id
S001           81.0     82.5     84.5
S002           73.5     72.0     75.0
S003           87.5     88.5     89.5
S004           68.5     67.5     69.5
S005           81.5     82.5     83.5
S006           76.0     75.0     77.0
S007           89.0     89.0     90.5
S008           71.0     70.0     72.0
S009           79.5     78.5     80.5
S010           84.5     85.5     86.5
S011           73.0     72.0     74.0
S012           80.5     79.5     81.5
S013           66.5     67.5     68.5
S014           91.5     92.5     93.5
S015           74.5     73.5     75.5
S016           83.0     84.0     85.0
S017           70.5     69.5     71.5
S018           77.0     78.0     79.0
S019           83.5     84.5     85.5
S020           71.5     70.5     72.5
S021           87.5     88.5     89.5
S022           69.5     68.5     70.5
S023           80.0     81.0     82.0
S024           73.5     72.5     74.5
S025           78.5     79.5     80.5
S026           69.5     70.5     71.5
S027           85.5     86.5     87.5
S028           74.5     75.5     76.5
S029           80.5     81.5     82.5
S030           72.5     73.5     74.5
S031           86.5     87.5     88.5
S032           71.5     70.5     72.5
S033           77.5     78.5     79.5
S034           83.5     84.5     85.5
S035           69.5     68.5     70.5
S036           75.5     74.5     76.5
S037           81.5     82.5     83.5
S038           70.5     69.5     71.5
S039           76.5     77.5     78.5
S040           83.5     84.5     85.5
S041           67.5     68.5     69.5
S042           74.5     73.5     75.5
S043           82.5     83.5     84.5
S044           71.5     70.5     72.5
S045           89.5     90.5     91.5
S046           73.5     72.5     74.5
S047           80.5     81.5     82.5
S048           68.5     67.5     69.5
S049           87.5     88.5     89.5
S050           75.5     74.5     76.5

In [19]:
rows_count=len(student_module_report)

In [20]:
unique_students=len(scores['student_id'].unique())

In [80]:
print("Are rows count and unique student count same:",rows_count==unique_students)

Are rows count and unique student count same: True

In [21]:
student_module_report.columns

Index(['Module1', 'Module2', 'Module3'], dtype='str', name='module')

TASK5

In [22]:
student_averages = scores.groupby(['cohort', 'student_id'])['score'].mean().reset_index()
student_averages.rename(columns={'score': 'avg_score'}, inplace=True)
student_averages['rank'] = student_averages.groupby('cohort')['avg_score'].rank(
    method='min',
    ascending=False
)
top_students = student_averages[student_averages['rank'] <= 3][['student_id', 'cohort', 'avg_score']]

In [23]:
top_students

   student_id cohort  avg_score
2        S003  alpha       88.5
10       S027  alpha       86.5
16       S049  alpha       88.5
17       S007   beta       89.5
23       S021   beta       88.5
31       S045   beta       90.5
35       S014  gamma       92.5
37       S016  gamma       84.0
45       S040  gamma       84.5

In [113]:
cohort_counts = top_students['cohort'].value_counts()
is_valid = (cohort_counts == 3).all()
is_valid#check cohort appear 3 times

np.True_